spring.application.name=gym-management-system
#db
spring.datasource.url=jdbc:mysql://localhost:3306/db_strke?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root@322-ABC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#jpa
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#thymeleaf
logging.level.org.thymeleaf=DEBUG