name: CI Pipeline - Gym Management System

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ejecutar pruebas
        run: mvn clean test

      - name: Construir aplicación
        run: mvn clean package -DskipTests